"""
response.py

Defines the structured response returned by the LLM layer.
"""

from dataclasses import dataclass, field
from typing import Any, Dict


@dataclass
class LLMResponse:
    """
    Represents a response generated by the local LLM.
    """

    query: str

    answer: str

    model: str

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    def to_dict(self):
        """
        Convert the response to a dictionary.
        """

        return {
            "query": self.query,
            "answer": self.answer,
            "model": self.model,
            "metadata": self.metadata,
        }

    def __str__(self):
        """
        Return a readable representation.
        """

        return (
            "LLM Response\n"
            f"Query  : {self.query}\n"
            f"Model  : {self.model}\n"
            f"Answer : {self.answer}\n"
            f"Metadata : {self.metadata}"
        )

    def __repr__(self):

        return (
            f"LLMResponse("
            f"model='{self.model}', "
            f"query='{self.query}')"
        )

    def __len__(self):
        """
        Return the length of the generated answer.
        """

        return len(self.answer)